name: CI Pipeline
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew build
        continue-on-error: true

      - name: Test Report
        uses: asadmansr/android-test-report-action@v1.2.0